#!/bin/sh

#
# This script computes the various flags needed to run GNU C++ testsuites
# (compiler specific as well as library specific). 
#
# Written by Benjamin Kosnik <bkoz@redhat.com>
#            Gabriel Dos Reis <gdr@codesourcery.com>
#

# Print a message saying how this script is intended to be invoked
print_usage() {
    cat <<EOF
Usage: 
    testsuite_flags --install-includes
		    --build-includes
		    --build-cxx
		    --build-cc
		    --install-cxx
		    --cxxflags
		    --cxxpchflags
		    --cxxldflags
EOF
}

# Establish configure-generated directory structure.
BUILD_DIR=/opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/libstdc++-v3
SRC_DIR=/opt/rtems-4.10/tool/gcc-4.4.7/libstdc++-v3
PREFIX_DIR=/opt/rtems-4.10
query=$1

case ${query} in
    --install-includes)
      INCLUDES="-I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --build-includes)
      INCLUDES="-nostdinc++ -I/opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/libstdc++-v3/include/sparc-rtems4.10 -I/opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/libstdc++-v3/include -I/opt/rtems-4.10/tool/gcc-4.4.7/libstdc++-v3/libsupc++ 
                -I${SRC_DIR}/include/backward -I${SRC_DIR}/testsuite/util"
      echo ${INCLUDES}
      ;;
    --install-cxx)
      CXX=${PREFIX_DIR}/bin/g++
      echo ${CXX}
      ;;
    --build-cxx)
      CXX_build="/opt/rtems-4.10/tool/b-gcc/./gcc/xgcc -shared-libgcc -B/opt/rtems-4.10/tool/b-gcc/./gcc -nostdinc++ -L/opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/libstdc++-v3/src -L/opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/libstdc++-v3/src/.libs -nostdinc -B/opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/newlib/ -isystem /opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/newlib/targ-include -isystem /opt/rtems-4.10/tool/gcc-4.4.7/newlib/libc/include -B/opt/rtems-4.10/sparc-rtems4.10/bin/ -B/opt/rtems-4.10/sparc-rtems4.10/lib/ -isystem /opt/rtems-4.10/sparc-rtems4.10/include -isystem /opt/rtems-4.10/sparc-rtems4.10/sys-include  -msoft-float -mcpu=v8"
      CXX=`echo "$CXX_build" | sed 's,gcc/xgcc ,gcc/g++ ,'`
      echo ${CXX}
      ;;
    --build-cc)
      CC_build="/opt/rtems-4.10/tool/b-gcc/./gcc/xgcc -B/opt/rtems-4.10/tool/b-gcc/./gcc/ -nostdinc -B/opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/newlib/ -isystem /opt/rtems-4.10/tool/b-gcc/sparc-rtems4.10/soft/v8/newlib/targ-include -isystem /opt/rtems-4.10/tool/gcc-4.4.7/newlib/libc/include -B/opt/rtems-4.10/sparc-rtems4.10/bin/ -B/opt/rtems-4.10/sparc-rtems4.10/lib/ -isystem /opt/rtems-4.10/sparc-rtems4.10/include -isystem /opt/rtems-4.10/sparc-rtems4.10/sys-include  -msoft-float -mcpu=v8"
      CC="$CC_build"
      echo ${CC}
      ;;
    --cxxflags)
      CXXFLAGS_default="-g -O2 -D_GLIBCXX_ASSERT -fmessage-length=0"
      CXXFLAGS_config="-ffunction-sections -fdata-sections -g -O2  "
      echo ${CXXFLAGS_default} ${CXXFLAGS_config}
      ;;
    --cxxparallelflags)
      CXXFLAGS_parallel="-D_GLIBCXX_PARALLEL -fopenmp
			 -B${BUILD_DIR}/../libgomp 
                         -I${BUILD_DIR}/../libgomp 
			 -L${BUILD_DIR}/../libgomp/.libs -lgomp"
      echo ${CXXFLAGS_parallel}
      ;;
    --cxxpchflags)
      PCHFLAGS="-include bits/stdc++.h"
      echo ${PCHFLAGS}
      ;;
    --cxxldflags)
      SECTIONLDFLAGS=" "
      echo ${SECTIONLDFLAGS}
      ;;
    *)
      print_usage
      ;;
esac

exit 0
