#
#  $Id: Makefile,v 1.1.1.1 2009/08/06 20:25:58 joel Exp $
#

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(RTEMS_ROOT)/make/directory.cfg

SUBDIRS=classic_signal triple_period
