#
#  $Id: Makefile,v 1.3 2009/08/06 23:23:35 joel Exp $
#

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(RTEMS_ROOT)/make/directory.cfg

SUBDIRS=classic_api posix_api hello led misc ticker file_io

# Monitor Specific Examples
SUBDIRS += uboot

# Language Specific Examples
SUBDIRS += cxx
